---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name: "{{ install_packages }}"
    state: present
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Cleanup packages.
  ansible.builtin.apt:
    name: "{{ cleanup_packages }}"
    state: absent
  environment:
    DEBIAN_FRONTEND: noninteractive
