---
- name: Example playbook
  hosts: all
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - role: cowdogmoo.vnc_zsh
    - role: l50.sliver
    - role: cowdogmoo.firefox
