---
name: Molecule Test
on:
  pull_request:
  push:
    branches: [main]

# defaults:
#   run:
#     working-directory: "cowdogmoo.vnc_zsh"

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Set up Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip3 install ansible molecule docker
          pip3 install molecule-docker

      - name: Install galaxy dependencies
        run: |
          ansible-galaxy install -v -r requirements.yml
          ansible-galaxy collection install -v -r requirements.yml

      - name: Test role with molecule
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: geerlingguy/docker-ubuntu2204-ansible
