---
name: Molecule Test
on:
  pull_request:
  push:
    branches: [main]

# defaults:
#   run:
#     working-directory: "cowdogmoo.vnc_zsh"

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip3 install ansible molecule docker
          pip3 install molecule-docker

      - name: Install galaxy dependencies
        run: ansible-galaxy install -r requirements.yaml

      - name: Test role with molecule
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: geerlingguy/docker-ubuntu2204-ansible
